spring:
  datasource:
    druid:
      url: jdbc:mysql://121.5.246.216:3309/tb_phone?useUnicode=true&characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: catchers.tech123
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
  redis:
    host: 121.5.246.216
    port: 6379
    database: 0
    password: "catchers.tech"
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  devtools:
    restart:
      additional-paths: src/main/java
logging:
  level:
    root: info
    com.dnslin.dnslin_api: debug
config:
  amap:
    key: "04f8bd06a2a5390ba589d6c0fb9bd3cf"
    privateKey: "9acba11d0c58ea7c10cad6ecbe19880b"
  Ipstack:
    Ipstackkey: "b6a76bd77214348a9a60ad29b51cac9a"
server:
  port: 5678
