spring:
  servlet:
    multipart:
      # 文件上传限制
      max-file-size: 100GB
      max-request-size: 100GB

  jpa:
    show-sql: true
  datasource:
    #  驱动
    driver-class-name: org.h2.Driver
    # h2 内存数据库 内存模式连接配置 库名: mybatis
    url: jdbc:h2:mem:one_manager;MODE=MySQL;
    # 初始化数据表 DDL
    schema: classpath:sql/init.sql
    #  初始化数据 DML
    data: classpath:sql/data.sql
    username: sa
    password: sa


  resources:
    static-locations: classpath:/
logging:
  level:
    root: info
    com.dnslin.onemanager: debug
server:
  port: 8881
  servlet:
    context-path: /oneManagerjava

onedrive:
  clientSecret: q847Q~yGYv6_GasCcKRaLF4syQUqpVz5D_HoH
  scope: offline_access User.Read openid Mail.Read
  redirectUri: http://localhost:8081/api/outlook
  clientId: 0d5e84db-18cf-4ab7-bc67-4af2dc9bce6b
  authenticateEndPoint: login.microsoftonline.com
  # 文件应用密钥信息
  file:
    clientSecret: wfy7Q~0R2MmSF6Zl3YRTcXxkGF0L8XOb_CL7k
    scope: offline_access Files.Read Files.ReadWrite Files.Read.All Files.ReadWrite.All
    redirectUri: https://ggball.top/oneManagerjava/api/file/auth
    clientId: 526c05e9-5e68-4178-aa62-43f70ba4ae96
    authenticateEndPoint: login.microsoftonline.com
microsoft-graph:
  root-url: https://graph.microsoft.com/v1.0
