name: CI

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master
env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # job名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    steps: #步骤
      - name: checkout # 拉取代码
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions

      - name: build with node.js # 编译vue
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          cache-dependency-path: src/main/resources/webapp/package-lock.json
          node-version: 12 # 版本
      - run: |
          cd src/main/resources/webapp
          npm install && npm run build-prod

      - name: build with maven # 编译 java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - run: mvn clean -DskipTests=true package

#      - name: build image
#
#
#


      - name: Install SSH Key # 设置coding ssh环境 方便ssh方式推送代码到coding
        uses: shimataro/ssh-key-action@v2.2.0
        with:
          key: ${{ secrets.CODING_ID_RSA }}
          known_hosts: ${{ secrets.CODING_HOSTS }}
      - run: |
          git remote rm origin
          git remote add origin git@e.coding.net:ggball/onemanager-java/Onemanager-java.git
          git config user.name ggball
          git config user.email 1667834841@qq.com
          git branch -a
          git push -f origin HEAD:master


#      - name: set SSH snvironment  设置ssh环境 无效
#        run: |
#          mkdir -p ~/.ssh/
#          echo "${{ secrets.CODING_ID_RSA }}" > ~/.ssh/id_rsa
#          echo "${{ secrets.CODING_ID_RSA_PUB }}" > ~/.ssh/id_rsa.pub
#          echo "${{ secrets.CODING_HOSTS}}" > ~/.ssh/konwn_hosts
#          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
#          chmod 600 ~/.ssh/id_rsa
#          chmod 700 ~/.ssh && chmod 700 ~/.ssh/*
#          ls -l ~/.ssh/


#
#      - name: deploy 将打包好的jar 发送到目标服务器 再执行脚本 scp速度太慢
#        uses: mdallasanta/ssh-scp-deploy@main
#        with:
#          local: '/home/runner/work/Onemanager-java/Onemanager-java/target/oneManager-java.jar'                                                  # Local file path - REQUIRED false - DEFAULT ./
#          remote: '/opt/jar'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
#          host: ${{secrets.DEPLOY_HOST}}                                      # Remote server address - REQUIRED true
#          port: ${{secrets.DEPLOY_PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
#          user: ${{secrets.DEPLOY_USER}}                                      # Remote server user - REQUIRED true
#          password: ${{secrets.DEPLOY_PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key"
#          key: ${{secrets.ID_RSA}}                                        # Remote server private key - REQUIRED at least one of "password" or "key"
#          pre_upload: echo "This will be executed before the upload!"  # Command to run via ssh before scp upload - REQUIRED false
#          post_upload: echo "This will be executed after the upload!"  # Command to run via ssh after scp upload - REQUIRED false
#          ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
#          scp_options: -v


