name: CI

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master
env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # job名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    steps: #步骤
      - name: checkout # 拉取代码
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions



      - name: Sync to Gitea
        uses: wearerequired/git-mirror-action@master
        env:
         # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
         SSH_PRIVATE_KEY: ${{ secrets.GITEA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:a1667834841/Onemanager-java.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitea.dongshanxia.top:35000/:ggball/onemanager-java.git
