name: CI

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master
env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # job名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    steps: #步骤
      - name: checkout # 拉取代码
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions


      - name: commit repo
        id: commit_repo
        run: |
          git config --global user.name "ggball"
          git config --global user.email "1667834841@qq.com"
          git init
          git add -A
          git commit -m "test"
          git push -f https://ggball:bc65cc90c76baba247e753c95ef5721200e97b59@gitea.dongshanxia.top:35000/ggball/onemanager-java.git master



