name: CI

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master
env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # job名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    steps: #步骤
      - name: checkout # 拉取代码
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions

#      - name: use node.js
#        uses: actions/setup-node@v1 # 作用：安装nodejs
#        with:
#          node-version: 12 # 版本
#
#      - name: build vue
#        run: |
#          chmod +x ./build_vue.sh
#          ./build_vue.sh
#
#      - name: use maven
#        uses: stCarolas/setup-maven@v4.2
#        with:
#          maven-version: 3.8.2
#
#      - name: build java
#        run: mvn clean -DskipTests=true package

      - name: Set SSH Environment
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          echo "${{ secrets.ID_RSA_PUB }}" > ~/.ssh/id_rsa.pub
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 700 ~/.ssh/*
          ls -l ~/.ssh/


